---

- ansible.builtin.include_role:
    name: alex.debian12.buildvm

- ansible.builtin.include_role: # install docker
    name: alex.debian12.installdocker

- ansible.builtin.include_role:
    name: alex.debian12.configureos

- ansible.builtin.include_role: # convert
    name: alex.proxmox.convert
