---

- ansible.builtin.include_role:
    name: alex.debian12.buildvm

- ansible.builtin.include_role: # configurebase
    name: alex.debian12.configureserver

- ansible.builtin.include_role:
    name: alex.debian12.configureos

- ansible.builtin.include_role: # convert
    name: alex.proxmox.convert

