---

- ansible.builtin.include_role:
    name: alex.debian12.buildvm

- ansible.builtin.include_role: # configurebase
    name: alex.debian12.configureserver

- ansible.builtin.include_role:
    name: alex.debian12.configureos

- ansible.builtin.include_role: # export
    name: alex.proxmox.exportvm

# - ansible.builtin.include_role: # remove
#     name: alex.proxmox.removevm
