---

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - ca-certificates 
    - curl
    - gnupg
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Add an Apt signing key from Docker
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    keyring: /etc/apt/trusted.gpg.d/docker-apt-key.gpg
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Add Docker repository (intel)
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable
    state: present
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - apache2-utils
    - docker-buildx-plugin
    - docker-compose-plugin
    - python3-requests
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Copy profile file
  ansible.builtin.template:
    src: "deamon.json.j2"
    dest: "/etc/docker/daemon.json"
    owner: root
    group: root
    mode: 0777
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true

- name: Configure Network
  shell: |
    docker network create \
      --driver=bridge \
      alex0
  args:
    executable: /bin/bash
  vars:
    ansible_connection: ssh
    ansible_host: "{{ prop_ipaddress }}"
  become: true



