---

- name: "Playbook: Build Debian 12 Server Template"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role:
        name: alex.debian12.buildservertemplate
