---

- name: "Playbook: Configure Debian 12 Base OS"
  hosts: "{{ args_host }}"
  gather_facts: false

  vars_files:
    - /etc/ansible/inventory/vars.yml

  tasks:
    - ansible.builtin.include_role:
        name: alex.debian12.configureserver
